/* Uses browser request interception for local checks: no localhost server or installs. */
const {chromium}=require('playwright');
const fs=require('node:fs'), path=require('node:path'), assert=require('node:assert/strict');
const base=process.env.GULLY_PREVIEW_URL || 'https://gully-preview.test/gully/';
const root=path.join(__dirname,'..','docs'), out=path.join(__dirname,'verification','baithak');
fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1050},timezoneId:'America/Chicago'});
 if(!process.env.GULLY_PREVIEW_URL) await context.route('https://gully-preview.test/gully/**', async route=>{
   const name=new URL(route.request().url()).pathname.split('/').pop() || 'index.html';
   if(!['index.html','styles.css','baithak.css','data.js','app.js','ui.js','baithak.js','interactions.js','icon.svg'].includes(name)) return route.abort();
   await route.fulfill({path:path.join(root,name),contentType:name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.svg')?'image/svg+xml':'text/html'});
 });
 const page=await context.newPage(), errors=[], checks=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('dialog',async dialog=>{errors.push('Unexpected browser dialog: '+dialog.message());await dialog.dismiss();});
 const pass=name=>{checks.push(name);console.log('PASS '+name);};
 const click=selector=>page.locator(selector).first().click();
 const ba=(action,id)=>`[data-ba="${action}"]${id?`[data-room="${id}"]`:''}`;
 const roomState=id=>page.evaluate(id=>state.baithak.rooms.find(r=>r.id===id),id);
 const go=async id=>{await page.evaluate(id=>nav('baithak',id),id);};
 const plusTime=async hours=>page.evaluate(hours=>new Date(Date.now()+hours*3600000+330*60000).toISOString().slice(0,16),hours);
 const submit=()=>page.locator('#ba-schedule').evaluate(form=>form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 async function fillPlan(title='First job in Hyderabad, a Baithak') {
   await page.locator('#ba-title').fill(title);
   await page.locator('#ba-description').fill('Sharing first-job stories, budget tips, and kind conversations with other Hyderabad freshers.');
   await page.locator('#ba-start').fill(await plusTime(14));
   await page.locator('#ba-schedule input[name="agree"]').check();
 }
 try {
  await page.clock.install({time:new Date('2026-09-18T15:59:59Z')});
  await page.clock.pauseAt(new Date('2026-09-18T16:00:00Z'));
  await page.goto(base+'#baithak');
  await page.locator('#age-form input[name="age"]').check();
  await page.locator('#age-form input[name="rules"]').check();
  await click('#age-form .btn-primary');
  assert.equal(await page.locator('.ba-card').count(),2);
  assert.equal(await page.locator('[data-ba-card="campus-after-hours"]').count(),0);
  assert.match(await page.locator('.ba-preview').innerText(),/Live audio is not connected/);
  pass('Discovery shows approved sessions only and identifies the local audio preview');
  await page.screenshot({path:path.join(out,'desktop-discovery.png'),fullPage:true});
  await click(ba('schedule')); await fillPlan();
  assert.match(await page.locator('#ba-plan-summary').innerText(),/IST/);
  await page.locator('#ba-start').fill(await plusTime(11)); await submit();
  assert.match(await page.locator('#ba-form-error').innerText(),/at least 12 hours/);
  assert.equal(await page.evaluate(()=>state.baithak.rooms.filter(r=>r.hostId==='local-self').length),0);
  pass('Application validation rejects less than 12 hours of notice');
  await page.locator('#ba-start').fill(await plusTime(14));
  await page.locator('#ba-duration').evaluate(select=>{select.add(new Option('90','90'));select.value='90';});await submit();
  assert.match(await page.locator('#ba-form-error').innerText(),/30, 45, or 60/);
  await page.locator('#ba-duration').selectOption('60');
  await page.locator('#ba-capacity').evaluate(select=>{select.add(new Option('31','31'));select.value='31';});await submit();
  assert.match(await page.locator('#ba-form-error').innerText(),/room size/);
  await page.locator('#ba-capacity').selectOption('30');
  await page.locator('#ba-title').fill('<img src=x onerror=alert(1)> First job stories');
  const input=await page.locator('#ba-start').inputValue();
  await submit();
  const own=await page.evaluate(()=>state.baithak.rooms.find(r=>r.hostId==='local-self'));
  assert.equal(own.status,'pending');assert.equal(own.duration,60);assert.equal(own.capacity,30);
  assert.equal(own.startsAt,Date.parse(input+':00+05:30'));
  assert.equal(await page.locator('img[src="x"]').count(),0);
  pass('Valid request persists, uses IST from a Chicago browser, escapes text, and enforces duration/capacity bounds');
  await page.reload();
  assert.match(await page.locator('.ba-status').first().innerText(),/Awaiting approval/);
  pass('Request survives reload and direct detail link');
  await go('review');
  await click(ba('approve',own.id)); assert.equal((await roomState(own.id)).status,'approved');
  await go(own.id); assert.equal(await page.locator(ba('start')).count(),0);
  pass('Admin simulation approves the request; approved hosts cannot open before the scheduled time');
  await click(ba('edit',own.id));
  await page.locator('#ba-title').fill('First-job stories, revised'); await page.locator('#ba-schedule input[name=agree]').check(); await submit();
  const revised=await roomState(own.id);assert.equal(revised.status,'pending');assert.equal(revised.reviewedAt,null);assert.equal(revised.revision,2);
  pass('Editing an approved request resets it to pending and clears approval');
  await go('review'); await click(ba('decline',own.id));
  await page.locator('#ba-review-note').fill('Please add clearer topic boundaries to help the conversation stay focused.');
  await click('#ba-decline button[type="submit"]');
  assert.equal((await roomState(own.id)).status,'declined');
  await go(own.id);assert.match(await page.locator('.ba-status-copy').innerText(),/clearer topic boundaries/);
  await click(ba('edit',own.id));await page.locator('#ba-schedule input[name=agree]').check();await submit();assert.equal((await roomState(own.id)).status,'pending');
  pass('Decline stores a reason and allows a fresh request for approval');
  await click(ba('back'));await click(ba('schedule'));await fillPlan('Another overlapping conversation');await submit();
  assert.match(await page.locator('#ba-form-error').innerText(),/already have/);
  await click('[data-action="close-modal"]');pass('Overlapping host requests are rejected');
  await go('pg-roundtable');await click(ba('save','pg-roundtable'));assert.equal((await roomState('pg-roundtable')).saved,true);
  const download=page.waitForEvent('download');await click(ba('calendar','pg-roundtable'));const calendar=await download;
  const file=path.join(out,'baithak.ics');await calendar.saveAs(file);const contents=fs.readFileSync(file,'utf8');
  assert.match(contents,/BEGIN:VEVENT/);assert.match(contents,/DTSTART:\d{8}T\d{6}Z/);assert.match(contents,/Frontend preview/);
  pass('Save to plans and real calendar download work without implying a seat reservation');
  await go('chai-break');
  await page.screenshot({path:path.join(out,'desktop-room.png'),fullPage:true});
  await click(ba('join','chai-break'));
  assert.equal((await roomState('chai-break')).members.filter(p=>p.id==='local-self').length,1);
  await click(ba('hand','chai-break'));assert.ok((await roomState('chai-break')).requests.includes('local-self'));
  await page.locator('.ba-demo-tools summary').click();await click(ba('host-preview','chai-break'));
  await click('[data-ba="approve-speaker"][data-person="local-self"]');
  let self=(await roomState('chai-break')).members.find(p=>p.id==='local-self');assert.equal(self.role,'speaker');assert.equal(self.muted,true);
  pass('Listener entry, raised hand, host invitation, and muted-by-default speaker work');
  await click(ba('self-mute','chai-break'));self=(await roomState('chai-break')).members.find(p=>p.id==='local-self');assert.equal(self.muted,false);
  await click('[data-ba="mute-person"][data-person="local-self"]');assert.equal((await roomState('chai-break')).members.find(p=>p.id==='local-self').muted,true);
  assert.ok(await page.locator('[data-ba="mute-person"][data-person="local-self"]').isDisabled());
  pass('Host can mute a speaker but cannot remotely unmute them');
  await page.evaluate(()=>{const r=state.baithak.rooms.find(r=>r.id==='chai-break');r.members.filter(p=>p.role==='listener').slice(0,2).forEach(p=>p.role='speaker');persist();refresh();});
  assert.equal((await roomState('chai-break')).members.filter(p=>p.role!=='listener').length,6);
  assert.ok(await page.locator('[data-ba="approve-speaker"]').first().isDisabled());pass('The stage is limited to six people including the host');
  await click('[data-ba="to-listener"][data-person="local-self"]');await click('[data-ba="remove-person"][data-person="local-self"]');
  assert.ok(await page.locator(ba('join','chai-break')).isDisabled());assert.ok((await roomState('chai-break')).removed.includes('local-self'));
  pass('Removed participants cannot rejoin the local room');
  await page.evaluate(()=>{const r=state.baithak.rooms.find(r=>r.id==='chai-break');r.removed=[];while(r.members.length<r.capacity)r.members.push({id:'fill-'+r.members.length,handle:'SampleListener'+r.members.length,avatar:0,role:'listener',muted:true});persist();refresh();});
  assert.equal(await page.locator(ba('join','chai-break')).innerText(),'Room is full');assert.ok(await page.locator(ba('join','chai-break')).isDisabled());
  pass('Room capacity includes the host and prevents listener admission when full');
  await click(ba('report','chai-break'));await page.locator('#ba-report-details').fill('Example report for preview testing.');await click('#ba-report button[type="submit"]');
  assert.equal(await page.evaluate(()=>state.baithak.reports.length),1);pass('Room reporting saves locally with an explicit delivery limitation');
  await click(ba('end','chai-break'));await click(ba('confirm-end','chai-break'));
  assert.match(await page.locator('.ba-status').first().innerText(),/Ended/);assert.equal((await roomState('chai-break')).requests.length,0);
  pass('Host confirmation ends the room and clears the speaker queue');
  await go('review');await click(ba('approve',own.id));
  const start=(await roomState(own.id)).startsAt;
  await page.clock.fastForward(start - Date.parse('2026-09-18T16:00:00Z') + 600000);
  await go(own.id);await click(ba('start',own.id));
  assert.match(await page.locator('#ba-countdown').innerText(),/^50:00$/);
  pass('Late start preserves the original scheduled end time');
  await page.clock.fastForward(50*60000+1000);
  assert.match(await page.locator('.ba-status').first().innerText(),/Ended/);
  assert.equal((await roomState(own.id)).endedAt,start+60*60000);
  await page.reload();assert.match(await page.locator('.ba-status').first().innerText(),/Ended/);
  pass('Automatic cutoff persists across reload and the room cannot reopen');
  await go('review');
  await page.clock.fastForward(30*3600000);
  await page.reload();assert.ok(await page.locator('[data-ba="approve"][data-room="campus-after-hours"]').isDisabled());
  pass('An unreviewed request expires and cannot be approved after its start');
  await go();await click(ba('schedule'));await fillPlan('A session to withdraw today');await page.locator('#ba-duration').selectOption('30');await page.locator('#ba-capacity').selectOption('15');await submit();
  const cancelledId=await page.evaluate(()=>state.baithak.rooms.at(-1).id);
  await click(ba('cancel',cancelledId));await click(ba('confirm-cancel',cancelledId));assert.equal((await roomState(cancelledId)).status,'cancelled');
  pass('Minimum duration/capacity are accepted and a host can withdraw a request');
  await page.evaluate(()=>{delete state.baithak;persist();});await go();await click(ba('tab','Upcoming'));
  for(const width of [360,390,768,1440]) {
   await page.setViewportSize({width,height:1000});
   for(const id of [undefined,'chai-break','pg-roundtable','review']) {
    await go(id);
    const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,`Overflow ${width}, ${id}`);
   }
   await go();await click(ba('schedule'));
   assert.equal(await page.evaluate(()=>document.querySelector('.modal').scrollWidth>document.querySelector('.modal').clientWidth+1),false);
   if(width===390) await page.screenshot({path:path.join(out,'mobile-schedule.png'),fullPage:true});
   await page.keyboard.press('Escape');assert.equal(await page.locator('.modal').count(),0);
   if(width===390) {await page.screenshot({path:path.join(out,'mobile-discovery.png'),fullPage:true});await go('chai-break');await page.screenshot({path:path.join(out,'mobile-room.png'),fullPage:true});}
  }
  pass('Discovery, room, request details, review desk and scheduling fit 360/390/768/1440px screens');
  await page.setViewportSize({width:390,height:900});await page.evaluate(()=>nav('home'));
  await click('.mobile-nav [data-nav="baithak"]');assert.equal(await page.locator('.ba-hero').count(),1);
  await page.evaluate(()=>nav('baithak','pg-roundtable'));await page.evaluate(()=>nav('baithak','weekend-deccan'));await page.goBack();
  assert.match(await page.locator('.ba-detail-body h2').innerText(),/PG dinner/);
  pass('Mobile navigation and browser Back resolve Baithak detail routes');
  assert.deepEqual(errors,[]);pass('No uncaught browser errors or unsafe HTML execution');
  fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({at:new Date().toISOString(),url:base,checks,errors},null,2));
  console.log(`${checks.length} checks passed.`);
 } catch(error) {await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});throw error;}
 finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
